// ExpenseCategories.js

const ExpenseCategories = [
    { value: "fnb", label: "Food and Beverage" },
    { value: "travel", label: "Travel" },
    { value: "rent", label: "Rent" },
    { value: "utilities", label: "Utilities" },
    { value: "office_supplies", label: "Office Supplies" },
    { value: "transportation", label: "Transportation" },
    { value: "entertainment", label: "Entertainment" },
    { value: "marketing", label: "Marketing" },
    { value: "healthcare", label: "Healthcare" },
    { value: "insurance", label: "Insurance" },
    { value: "education", label: "Education" },
    { value: "subscriptions", label: "Subscriptions" },
    { value: "maintenance_repairs", label: "Maintenance and Repairs" },
    { value: "technology", label: "Technology and Software" },
    { value: "employee_salaries", label: "Employee Salaries" },
    { value: "bank_fees", label: "Bank Fees" },
    { value: "taxes", label: "Taxes" },
    { value: "legal_fees", label: "Legal Fees" },
    { value: "professional_services", label: "Professional Services" },
    { value: "charity_donations", label: "Charity/Donations" },
    { value: "groceries", label: "Groceries" },
    { value: "dining_out", label: "Dining Out" },
    { value: "shopping", label: "Shopping" },
    { value: "fitness_health", label: "Fitness/Health" },
    { value: "personal_care", label: "Personal Care" },
    { value: "pet_care", label: "Pet Care" },
    { value: "childcare", label: "Childcare" },
    { value: "home_improvement", label: "Home Improvement" },
    { value: "salaries_wages", label: "Salaries and Wages" },
    { value: "freelancer_payments", label: "Freelancer Payments" },
    { value: "client_meals", label: "Client Meals" },
    { value: "networking", label: "Networking" },
    { value: "conference_fees", label: "Conference Fees" },
    { value: "advertising", label: "Advertising" },
    { value: "sales_commissions", label: "Sales Commissions" },
    { value: "product_development", label: "Product Development" },
    { value: "gifts_donations", label: "Gifts and Donations" },
    { value: "miscellaneous_expenses", label: "Miscellaneous Expenses" },
    { value: "contingency_fund", label: "Contingency Fund" },
];


export default ExpenseCategories;
