import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import React, { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
        <AuthProvider>
          <body>
            {children}
          </body>
        </AuthProvider>

    </html>
  );
}
